services:
  - type: web
    name: myBackend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements/requirements.txt
    startCommand: gunicorn API.endpoints:app
    envVars:
      - key: DB_ENV
        value: remote
      - key: DATABASE_URL
        value: postgresql://postgres.xfyaizroguvnlekxuouu:denislabmyBackend@aws-1-us-east-1.pooler.supabase.com:6543/postgres
databases:
  - name: myDatabase
    plan: free